apiVersion: batch/v1
kind: CronJob
metadata:
  name: loadgeneratorservice
  labels:
    dt.owner: hipster-shop
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: loadgenerator
            product: k6
            dt.owner: hipster-shop
          annotations:
            oneagent.dynatrace.com/inject: "false"
        spec:
          terminationGracePeriodSeconds: 5
          restartPolicy: OnFailure
          containers:
            - name: k6load
              image: hrexed/k6-todo-demo:0.8
              imagePullPolicy: Always
              args: [ "-u", "10", "-d", "59m" ]
              env:
                - name: HOST_HEADER
                  value: "postddemo.IP_TO_REPLACE.nip.io"
                - name: FRONTEND_ADDR
                  value: "postddemo.IP_TO_REPLACE.nip.io"
                - name: K6_DYNATRACE_URL
                  valueFrom:
                    secretKeyRef:
                      name: dynatrace
                      key: dynatrace_oltp_url
                - name: K6_DYNATRACE_INSECURE_SKIP_TLS_VERIFY
                  value: "true"
                - name: K6_DYNATRACE_APITOKEN
                  valueFrom:
                    secretKeyRef:
                      name: dynatrace
                      key: dt_api_token
              resources:
                requests:
                  cpu: 100m
                  memory: 64Mi
                limits:
                  cpu: 200m
                  memory: 128Mi
---